// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tg.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Response struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_tg_8558066898e1d2ee, []int{0}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type TgUpdate struct {
	UpdateID             int32      `protobuf:"varint,1,opt,name=UpdateID,proto3" json:"UpdateID,omitempty"`
	Message              *TgMessage `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TgUpdate) Reset()         { *m = TgUpdate{} }
func (m *TgUpdate) String() string { return proto.CompactTextString(m) }
func (*TgUpdate) ProtoMessage()    {}
func (*TgUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_tg_8558066898e1d2ee, []int{1}
}
func (m *TgUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TgUpdate.Unmarshal(m, b)
}
func (m *TgUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TgUpdate.Marshal(b, m, deterministic)
}
func (dst *TgUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TgUpdate.Merge(dst, src)
}
func (m *TgUpdate) XXX_Size() int {
	return xxx_messageInfo_TgUpdate.Size(m)
}
func (m *TgUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_TgUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_TgUpdate proto.InternalMessageInfo

func (m *TgUpdate) GetUpdateID() int32 {
	if m != nil {
		return m.UpdateID
	}
	return 0
}

func (m *TgUpdate) GetMessage() *TgMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

type TgMessage struct {
	MessageID              uint64     `protobuf:"varint,1,opt,name=messageID,proto3" json:"messageID,omitempty"`
	From                   *TgFrom    `protobuf:"bytes,2,opt,name=From,proto3" json:"From,omitempty"`
	Date                   uint64     `protobuf:"varint,3,opt,name=Date,proto3" json:"Date,omitempty"`
	Chat                   *TgChat    `protobuf:"bytes,4,opt,name=Chat,proto3" json:"Chat,omitempty"`
	ForwardedFrom          *TgUser    `protobuf:"bytes,5,opt,name=ForwardedFrom,proto3" json:"ForwardedFrom,omitempty"`
	ForwardedFromChat      *TgChat    `protobuf:"bytes,6,opt,name=ForwardedFromChat,proto3" json:"ForwardedFromChat,omitempty"`
	ForwardedFromMessageID int64      `protobuf:"varint,7,opt,name=ForwardedFromMessageID,proto3" json:"ForwardedFromMessageID,omitempty"`
	ForwardDate            uint64     `protobuf:"varint,8,opt,name=ForwardDate,proto3" json:"ForwardDate,omitempty"`
	ReplyToMessage         *TgMessage `protobuf:"bytes,9,opt,name=ReplyToMessage,proto3" json:"ReplyToMessage,omitempty"`
	EditDate               uint64     `protobuf:"varint,10,opt,name=EditDate,proto3" json:"EditDate,omitempty"`
	Text                   string     `protobuf:"bytes,11,opt,name=Text,proto3" json:"Text,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}   `json:"-"`
	XXX_unrecognized       []byte     `json:"-"`
	XXX_sizecache          int32      `json:"-"`
}

func (m *TgMessage) Reset()         { *m = TgMessage{} }
func (m *TgMessage) String() string { return proto.CompactTextString(m) }
func (*TgMessage) ProtoMessage()    {}
func (*TgMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_tg_8558066898e1d2ee, []int{2}
}
func (m *TgMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TgMessage.Unmarshal(m, b)
}
func (m *TgMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TgMessage.Marshal(b, m, deterministic)
}
func (dst *TgMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TgMessage.Merge(dst, src)
}
func (m *TgMessage) XXX_Size() int {
	return xxx_messageInfo_TgMessage.Size(m)
}
func (m *TgMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TgMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TgMessage proto.InternalMessageInfo

func (m *TgMessage) GetMessageID() uint64 {
	if m != nil {
		return m.MessageID
	}
	return 0
}

func (m *TgMessage) GetFrom() *TgFrom {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *TgMessage) GetDate() uint64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *TgMessage) GetChat() *TgChat {
	if m != nil {
		return m.Chat
	}
	return nil
}

func (m *TgMessage) GetForwardedFrom() *TgUser {
	if m != nil {
		return m.ForwardedFrom
	}
	return nil
}

func (m *TgMessage) GetForwardedFromChat() *TgChat {
	if m != nil {
		return m.ForwardedFromChat
	}
	return nil
}

func (m *TgMessage) GetForwardedFromMessageID() int64 {
	if m != nil {
		return m.ForwardedFromMessageID
	}
	return 0
}

func (m *TgMessage) GetForwardDate() uint64 {
	if m != nil {
		return m.ForwardDate
	}
	return 0
}

func (m *TgMessage) GetReplyToMessage() *TgMessage {
	if m != nil {
		return m.ReplyToMessage
	}
	return nil
}

func (m *TgMessage) GetEditDate() uint64 {
	if m != nil {
		return m.EditDate
	}
	return 0
}

func (m *TgMessage) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type TgFrom struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	FristName            string   `protobuf:"bytes,2,opt,name=FristName,proto3" json:"FristName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=LastName,proto3" json:"LastName,omitempty"`
	UserName             string   `protobuf:"bytes,4,opt,name=UserName,proto3" json:"UserName,omitempty"`
	LanguageCode         string   `protobuf:"bytes,5,opt,name=LanguageCode,proto3" json:"LanguageCode,omitempty"`
	IsBot                bool     `protobuf:"varint,6,opt,name=isBot,proto3" json:"isBot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TgFrom) Reset()         { *m = TgFrom{} }
func (m *TgFrom) String() string { return proto.CompactTextString(m) }
func (*TgFrom) ProtoMessage()    {}
func (*TgFrom) Descriptor() ([]byte, []int) {
	return fileDescriptor_tg_8558066898e1d2ee, []int{3}
}
func (m *TgFrom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TgFrom.Unmarshal(m, b)
}
func (m *TgFrom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TgFrom.Marshal(b, m, deterministic)
}
func (dst *TgFrom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TgFrom.Merge(dst, src)
}
func (m *TgFrom) XXX_Size() int {
	return xxx_messageInfo_TgFrom.Size(m)
}
func (m *TgFrom) XXX_DiscardUnknown() {
	xxx_messageInfo_TgFrom.DiscardUnknown(m)
}

var xxx_messageInfo_TgFrom proto.InternalMessageInfo

func (m *TgFrom) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *TgFrom) GetFristName() string {
	if m != nil {
		return m.FristName
	}
	return ""
}

func (m *TgFrom) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *TgFrom) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *TgFrom) GetLanguageCode() string {
	if m != nil {
		return m.LanguageCode
	}
	return ""
}

func (m *TgFrom) GetIsBot() bool {
	if m != nil {
		return m.IsBot
	}
	return false
}

type TgChat struct {
	ID                   int64        `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Type                 string       `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Title                string       `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	UserName             string       `protobuf:"bytes,4,opt,name=UserName,proto3" json:"UserName,omitempty"`
	FirstName            string       `protobuf:"bytes,5,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string       `protobuf:"bytes,6,opt,name=LastName,proto3" json:"LastName,omitempty"`
	AllMembersAreAdmins  bool         `protobuf:"varint,7,opt,name=AllMembersAreAdmins,proto3" json:"AllMembersAreAdmins,omitempty"`
	Photo                *TgChatPhoto `protobuf:"bytes,8,opt,name=Photo,proto3" json:"Photo,omitempty"`
	Description          string       `protobuf:"bytes,9,opt,name=Description,proto3" json:"Description,omitempty"`
	InviteLink           string       `protobuf:"bytes,10,opt,name=InviteLink,proto3" json:"InviteLink,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TgChat) Reset()         { *m = TgChat{} }
func (m *TgChat) String() string { return proto.CompactTextString(m) }
func (*TgChat) ProtoMessage()    {}
func (*TgChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_tg_8558066898e1d2ee, []int{4}
}
func (m *TgChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TgChat.Unmarshal(m, b)
}
func (m *TgChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TgChat.Marshal(b, m, deterministic)
}
func (dst *TgChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TgChat.Merge(dst, src)
}
func (m *TgChat) XXX_Size() int {
	return xxx_messageInfo_TgChat.Size(m)
}
func (m *TgChat) XXX_DiscardUnknown() {
	xxx_messageInfo_TgChat.DiscardUnknown(m)
}

var xxx_messageInfo_TgChat proto.InternalMessageInfo

func (m *TgChat) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *TgChat) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TgChat) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TgChat) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *TgChat) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *TgChat) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *TgChat) GetAllMembersAreAdmins() bool {
	if m != nil {
		return m.AllMembersAreAdmins
	}
	return false
}

func (m *TgChat) GetPhoto() *TgChatPhoto {
	if m != nil {
		return m.Photo
	}
	return nil
}

func (m *TgChat) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TgChat) GetInviteLink() string {
	if m != nil {
		return m.InviteLink
	}
	return ""
}

type TgChatPhoto struct {
	SmallFileID          string   `protobuf:"bytes,1,opt,name=SmallFileID,proto3" json:"SmallFileID,omitempty"`
	BigFileID            string   `protobuf:"bytes,2,opt,name=BigFileID,proto3" json:"BigFileID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TgChatPhoto) Reset()         { *m = TgChatPhoto{} }
func (m *TgChatPhoto) String() string { return proto.CompactTextString(m) }
func (*TgChatPhoto) ProtoMessage()    {}
func (*TgChatPhoto) Descriptor() ([]byte, []int) {
	return fileDescriptor_tg_8558066898e1d2ee, []int{5}
}
func (m *TgChatPhoto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TgChatPhoto.Unmarshal(m, b)
}
func (m *TgChatPhoto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TgChatPhoto.Marshal(b, m, deterministic)
}
func (dst *TgChatPhoto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TgChatPhoto.Merge(dst, src)
}
func (m *TgChatPhoto) XXX_Size() int {
	return xxx_messageInfo_TgChatPhoto.Size(m)
}
func (m *TgChatPhoto) XXX_DiscardUnknown() {
	xxx_messageInfo_TgChatPhoto.DiscardUnknown(m)
}

var xxx_messageInfo_TgChatPhoto proto.InternalMessageInfo

func (m *TgChatPhoto) GetSmallFileID() string {
	if m != nil {
		return m.SmallFileID
	}
	return ""
}

func (m *TgChatPhoto) GetBigFileID() string {
	if m != nil {
		return m.BigFileID
	}
	return ""
}

type TgUser struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=LastName,proto3" json:"LastName,omitempty"`
	UserName             string   `protobuf:"bytes,4,opt,name=UserName,proto3" json:"UserName,omitempty"`
	LanguageCode         string   `protobuf:"bytes,5,opt,name=LanguageCode,proto3" json:"LanguageCode,omitempty"`
	IsBot                bool     `protobuf:"varint,6,opt,name=IsBot,proto3" json:"IsBot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TgUser) Reset()         { *m = TgUser{} }
func (m *TgUser) String() string { return proto.CompactTextString(m) }
func (*TgUser) ProtoMessage()    {}
func (*TgUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_tg_8558066898e1d2ee, []int{6}
}
func (m *TgUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TgUser.Unmarshal(m, b)
}
func (m *TgUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TgUser.Marshal(b, m, deterministic)
}
func (dst *TgUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TgUser.Merge(dst, src)
}
func (m *TgUser) XXX_Size() int {
	return xxx_messageInfo_TgUser.Size(m)
}
func (m *TgUser) XXX_DiscardUnknown() {
	xxx_messageInfo_TgUser.DiscardUnknown(m)
}

var xxx_messageInfo_TgUser proto.InternalMessageInfo

func (m *TgUser) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *TgUser) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *TgUser) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *TgUser) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *TgUser) GetLanguageCode() string {
	if m != nil {
		return m.LanguageCode
	}
	return ""
}

func (m *TgUser) GetIsBot() bool {
	if m != nil {
		return m.IsBot
	}
	return false
}

func init() {
	proto.RegisterType((*Response)(nil), "proto.Response")
	proto.RegisterType((*TgUpdate)(nil), "proto.TgUpdate")
	proto.RegisterType((*TgMessage)(nil), "proto.TgMessage")
	proto.RegisterType((*TgFrom)(nil), "proto.TgFrom")
	proto.RegisterType((*TgChat)(nil), "proto.TgChat")
	proto.RegisterType((*TgChatPhoto)(nil), "proto.TgChatPhoto")
	proto.RegisterType((*TgUser)(nil), "proto.TgUser")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommandsClient is the client API for Commands service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommandsClient interface {
	Command(ctx context.Context, in *TgUpdate, opts ...grpc.CallOption) (*Response, error)
}

type commandsClient struct {
	cc *grpc.ClientConn
}

func NewCommandsClient(cc *grpc.ClientConn) CommandsClient {
	return &commandsClient{cc}
}

func (c *commandsClient) Command(ctx context.Context, in *TgUpdate, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.Commands/Command", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommandsServer is the server API for Commands service.
type CommandsServer interface {
	Command(context.Context, *TgUpdate) (*Response, error)
}

func RegisterCommandsServer(s *grpc.Server, srv CommandsServer) {
	s.RegisterService(&_Commands_serviceDesc, srv)
}

func _Commands_Command_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TgUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandsServer).Command(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Commands/Command",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandsServer).Command(ctx, req.(*TgUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

var _Commands_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Commands",
	HandlerType: (*CommandsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Command",
			Handler:    _Commands_Command_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tg.proto",
}

func init() { proto.RegisterFile("tg.proto", fileDescriptor_tg_8558066898e1d2ee) }

var fileDescriptor_tg_8558066898e1d2ee = []byte{
	// 575 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xdd, 0x8a, 0xd3, 0x40,
	0x14, 0x36, 0x6d, 0xd3, 0x26, 0xa7, 0xee, 0xaa, 0xa3, 0x2c, 0x65, 0x11, 0xa9, 0xb9, 0x2a, 0x82,
	0x8b, 0x74, 0x41, 0x14, 0xaf, 0xba, 0xad, 0x85, 0x42, 0x2b, 0x32, 0x76, 0x1f, 0x60, 0xd6, 0x0c,
	0xd9, 0xc1, 0x24, 0x13, 0x66, 0x66, 0xd5, 0x7d, 0x23, 0x9f, 0x40, 0xf0, 0xed, 0x64, 0x4e, 0x26,
	0x69, 0xd2, 0xfd, 0xb9, 0xdb, 0xab, 0x9e, 0xf3, 0x7d, 0x27, 0xe7, 0xef, 0x3b, 0x1d, 0x08, 0x4c,
	0x72, 0x52, 0x28, 0x69, 0x24, 0xf1, 0xf1, 0x27, 0x8a, 0x20, 0xa0, 0x5c, 0x17, 0x32, 0xd7, 0x9c,
	0x1c, 0x41, 0x5f, 0x1b, 0x66, 0xae, 0xf4, 0xc8, 0x1b, 0x7b, 0x93, 0x80, 0x3a, 0x2f, 0xa2, 0x10,
	0x6c, 0x93, 0xf3, 0x22, 0x66, 0x86, 0x93, 0x63, 0x08, 0x4a, 0x6b, 0xb5, 0xc0, 0x28, 0x9f, 0xd6,
	0x3e, 0x79, 0x03, 0x83, 0x0d, 0xd7, 0x9a, 0x25, 0x7c, 0xd4, 0x19, 0x7b, 0x93, 0xe1, 0xf4, 0x69,
	0x59, 0xeb, 0x64, 0x9b, 0x38, 0x9c, 0x56, 0x01, 0xd1, 0xbf, 0x2e, 0x84, 0x35, 0x4c, 0x5e, 0x42,
	0x98, 0x95, 0xa6, 0x4b, 0xdb, 0xa3, 0x3b, 0x80, 0xbc, 0x86, 0xde, 0x52, 0xc9, 0xcc, 0x25, 0x3d,
	0xa8, 0x93, 0x5a, 0x90, 0x22, 0x45, 0x08, 0xf4, 0x16, 0xcc, 0xf0, 0x51, 0x17, 0xbf, 0x45, 0xdb,
	0x7e, 0x36, 0xbf, 0x64, 0x66, 0xd4, 0xdb, 0xfb, 0xcc, 0x82, 0x14, 0x29, 0x72, 0x0a, 0x07, 0x4b,
	0xa9, 0x7e, 0x31, 0x15, 0xf3, 0x18, 0x4b, 0xf8, 0x7b, 0xb1, 0xe7, 0x9a, 0x2b, 0xda, 0x8e, 0x21,
	0x9f, 0xe0, 0x59, 0x0b, 0xc0, 0x22, 0xfd, 0xdb, 0x8a, 0xdc, 0x8c, 0x23, 0xef, 0xe1, 0xa8, 0x05,
	0x6e, 0xea, 0xb1, 0x07, 0x63, 0x6f, 0xd2, 0xa5, 0x77, 0xb0, 0x64, 0x0c, 0x43, 0xc7, 0xe0, 0x9c,
	0x01, 0xce, 0xd9, 0x84, 0xc8, 0x07, 0x38, 0xa4, 0xbc, 0x48, 0xaf, 0xb7, 0xb2, 0x12, 0x21, 0xbc,
	0x43, 0x84, 0xbd, 0x38, 0xab, 0xe9, 0xe7, 0x58, 0x18, 0x4c, 0x0c, 0x98, 0xb8, 0xf6, 0xed, 0x62,
	0xb7, 0xfc, 0xb7, 0x19, 0x0d, 0xc7, 0xde, 0x24, 0xa4, 0x68, 0x47, 0x7f, 0x3c, 0xe8, 0x97, 0xdb,
	0x27, 0x87, 0xd0, 0xa9, 0x15, 0xeb, 0xac, 0x16, 0x56, 0xc8, 0xa5, 0x12, 0xda, 0x7c, 0x61, 0x59,
	0x79, 0x04, 0x21, 0xdd, 0x01, 0xb6, 0xd0, 0x9a, 0x39, 0xb2, 0x8b, 0x64, 0xed, 0xe3, 0x61, 0x69,
	0xae, 0x90, 0xeb, 0x95, 0x5c, 0xe5, 0x93, 0x08, 0x1e, 0xaf, 0x59, 0x9e, 0x5c, 0xb1, 0x84, 0xcf,
	0x65, 0xcc, 0x51, 0xa5, 0x90, 0xb6, 0x30, 0xf2, 0x02, 0x7c, 0xa1, 0xcf, 0x64, 0xa9, 0x44, 0x40,
	0x4b, 0x27, 0xfa, 0xdb, 0xb1, 0xad, 0xe2, 0xe6, 0x77, 0xad, 0x76, 0xb1, 0x55, 0x3b, 0xd9, 0x75,
	0x51, 0x75, 0x89, 0xb6, 0x4d, 0xb2, 0x15, 0x26, 0xad, 0xba, 0x2b, 0x9d, 0x7b, 0x5b, 0xb3, 0x03,
	0x0b, 0xe5, 0x66, 0xf2, 0xdd, 0xc0, 0x15, 0xd0, 0x1a, 0xb8, 0xbf, 0x37, 0xf0, 0x3b, 0x78, 0x3e,
	0x4b, 0xd3, 0x0d, 0xcf, 0x2e, 0xb8, 0xd2, 0x33, 0xc5, 0x67, 0x71, 0x26, 0x72, 0x8d, 0x67, 0x10,
	0xd0, 0xdb, 0x28, 0x32, 0x01, 0xff, 0xeb, 0xa5, 0x34, 0x12, 0xd5, 0x1f, 0x4e, 0x49, 0xeb, 0xd8,
	0x90, 0xa1, 0x65, 0x80, 0xbd, 0x96, 0x05, 0xd7, 0xdf, 0x95, 0x28, 0x8c, 0x90, 0x39, 0x1e, 0x42,
	0x48, 0x9b, 0x10, 0x79, 0x05, 0xb0, 0xca, 0x7f, 0x0a, 0xc3, 0xd7, 0x22, 0xff, 0x81, 0xaa, 0x87,
	0xb4, 0x81, 0x44, 0x1b, 0x18, 0x36, 0xf2, 0xda, 0x84, 0xdf, 0x32, 0x96, 0xa6, 0x4b, 0x91, 0x56,
	0x7f, 0xd1, 0x90, 0x36, 0x21, 0xbb, 0x88, 0x33, 0x91, 0x38, 0xde, 0x29, 0x5f, 0x03, 0xee, 0x64,
	0xec, 0xd6, 0x6e, 0xe8, 0xd0, 0xda, 0x60, 0xe7, 0xbe, 0x0d, 0x3e, 0xc0, 0xc9, 0xac, 0x9a, 0x27,
	0x83, 0xce, 0xf4, 0x23, 0x04, 0x73, 0x99, 0x65, 0x2c, 0x8f, 0x35, 0x79, 0x0b, 0x03, 0x67, 0x93,
	0x27, 0xbb, 0x37, 0x01, 0xdf, 0xbb, 0xe3, 0x0a, 0xa8, 0x9e, 0xcf, 0xe8, 0xd1, 0x45, 0x1f, 0x91,
	0xd3, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x9f, 0x68, 0xc8, 0x66, 0x05, 0x00, 0x00,
}
