// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tg.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Response struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_tg_7cb0180f9eac2d34, []int{0}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type TgUpdate struct {
	UpdateID             int32      `protobuf:"varint,1,opt,name=UpdateID,proto3" json:"UpdateID,omitempty"`
	Message              *TgMessage `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TgUpdate) Reset()         { *m = TgUpdate{} }
func (m *TgUpdate) String() string { return proto.CompactTextString(m) }
func (*TgUpdate) ProtoMessage()    {}
func (*TgUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_tg_7cb0180f9eac2d34, []int{1}
}
func (m *TgUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TgUpdate.Unmarshal(m, b)
}
func (m *TgUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TgUpdate.Marshal(b, m, deterministic)
}
func (dst *TgUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TgUpdate.Merge(dst, src)
}
func (m *TgUpdate) XXX_Size() int {
	return xxx_messageInfo_TgUpdate.Size(m)
}
func (m *TgUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_TgUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_TgUpdate proto.InternalMessageInfo

func (m *TgUpdate) GetUpdateID() int32 {
	if m != nil {
		return m.UpdateID
	}
	return 0
}

func (m *TgUpdate) GetMessage() *TgMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

type TgMessage struct {
	MessageID              uint64           `protobuf:"varint,1,opt,name=messageID,proto3" json:"messageID,omitempty"`
	From                   *TgFrom          `protobuf:"bytes,2,opt,name=From,proto3" json:"From,omitempty"`
	Date                   int32            `protobuf:"varint,3,opt,name=Date,proto3" json:"Date,omitempty"`
	Chat                   *TgChat          `protobuf:"bytes,4,opt,name=Chat,proto3" json:"Chat,omitempty"`
	ForwardedFrom          *TgUser          `protobuf:"bytes,5,opt,name=ForwardedFrom,proto3" json:"ForwardedFrom,omitempty"`
	ForwardedFromChat      *TgChat          `protobuf:"bytes,6,opt,name=ForwardedFromChat,proto3" json:"ForwardedFromChat,omitempty"`
	ForwardedFromMessageID int64            `protobuf:"varint,7,opt,name=ForwardedFromMessageID,proto3" json:"ForwardedFromMessageID,omitempty"`
	ForwardDate            uint64           `protobuf:"varint,8,opt,name=ForwardDate,proto3" json:"ForwardDate,omitempty"`
	ReplyToMessage         *TgMessage       `protobuf:"bytes,9,opt,name=ReplyToMessage,proto3" json:"ReplyToMessage,omitempty"`
	EditDate               uint64           `protobuf:"varint,10,opt,name=EditDate,proto3" json:"EditDate,omitempty"`
	Text                   string           `protobuf:"bytes,11,opt,name=Text,proto3" json:"Text,omitempty"`
	Entities               []*MessageEntity `protobuf:"bytes,12,rep,name=Entities,proto3" json:"Entities,omitempty"`
	Audio                  *TgAudio         `protobuf:"bytes,13,opt,name=Audio,proto3" json:"Audio,omitempty"`
	Document               *TgDocument      `protobuf:"bytes,14,opt,name=Document,proto3" json:"Document,omitempty"`
	// @TODO(Kirill): Implement Game
	Photo   []*TgPhotoSize `protobuf:"bytes,15,rep,name=Photo,proto3" json:"Photo,omitempty"`
	Sticker *TgSticker     `protobuf:"bytes,16,opt,name=Sticker,proto3" json:"Sticker,omitempty"`
	// @TODO(Kirill): Implement Video
	// @TODO(Kirill): Implement VideoNote
	// @TODO(Kirill): Implement Voice
	Caption string `protobuf:"bytes,17,opt,name=Caption,proto3" json:"Caption,omitempty"`
	// @TODO(Kirill): Implement Contact
	// @TODO(Kirill): Implement Venue
	NewChatMembers        []*TgUser      `protobuf:"bytes,18,rep,name=NewChatMembers,proto3" json:"NewChatMembers,omitempty"`
	LeftChatMember        *TgUser        `protobuf:"bytes,19,opt,name=LeftChatMember,proto3" json:"LeftChatMember,omitempty"`
	NewChatTitle          string         `protobuf:"bytes,20,opt,name=NewChatTitle,proto3" json:"NewChatTitle,omitempty"`
	NewChatPhoto          []*TgPhotoSize `protobuf:"bytes,21,rep,name=NewChatPhoto,proto3" json:"NewChatPhoto,omitempty"`
	DeleteChatPhoto       bool           `protobuf:"varint,22,opt,name=DeleteChatPhoto,proto3" json:"DeleteChatPhoto,omitempty"`
	GroupChatCreated      bool           `protobuf:"varint,23,opt,name=GroupChatCreated,proto3" json:"GroupChatCreated,omitempty"`
	SuperGroupChatCreated bool           `protobuf:"varint,24,opt,name=SuperGroupChatCreated,proto3" json:"SuperGroupChatCreated,omitempty"`
	ChannelChatCreated    bool           `protobuf:"varint,25,opt,name=ChannelChatCreated,proto3" json:"ChannelChatCreated,omitempty"`
	MigrateToChatID       int64          `protobuf:"varint,26,opt,name=MigrateToChatID,proto3" json:"MigrateToChatID,omitempty"`
	MigrateFromChatID     int64          `protobuf:"varint,27,opt,name=MigrateFromChatID,proto3" json:"MigrateFromChatID,omitempty"`
	PinnedMessage         *TgMessage     `protobuf:"bytes,28,opt,name=PinnedMessage,proto3" json:"PinnedMessage,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}       `json:"-"`
	XXX_unrecognized      []byte         `json:"-"`
	XXX_sizecache         int32          `json:"-"`
}

func (m *TgMessage) Reset()         { *m = TgMessage{} }
func (m *TgMessage) String() string { return proto.CompactTextString(m) }
func (*TgMessage) ProtoMessage()    {}
func (*TgMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_tg_7cb0180f9eac2d34, []int{2}
}
func (m *TgMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TgMessage.Unmarshal(m, b)
}
func (m *TgMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TgMessage.Marshal(b, m, deterministic)
}
func (dst *TgMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TgMessage.Merge(dst, src)
}
func (m *TgMessage) XXX_Size() int {
	return xxx_messageInfo_TgMessage.Size(m)
}
func (m *TgMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TgMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TgMessage proto.InternalMessageInfo

func (m *TgMessage) GetMessageID() uint64 {
	if m != nil {
		return m.MessageID
	}
	return 0
}

func (m *TgMessage) GetFrom() *TgFrom {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *TgMessage) GetDate() int32 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *TgMessage) GetChat() *TgChat {
	if m != nil {
		return m.Chat
	}
	return nil
}

func (m *TgMessage) GetForwardedFrom() *TgUser {
	if m != nil {
		return m.ForwardedFrom
	}
	return nil
}

func (m *TgMessage) GetForwardedFromChat() *TgChat {
	if m != nil {
		return m.ForwardedFromChat
	}
	return nil
}

func (m *TgMessage) GetForwardedFromMessageID() int64 {
	if m != nil {
		return m.ForwardedFromMessageID
	}
	return 0
}

func (m *TgMessage) GetForwardDate() uint64 {
	if m != nil {
		return m.ForwardDate
	}
	return 0
}

func (m *TgMessage) GetReplyToMessage() *TgMessage {
	if m != nil {
		return m.ReplyToMessage
	}
	return nil
}

func (m *TgMessage) GetEditDate() uint64 {
	if m != nil {
		return m.EditDate
	}
	return 0
}

func (m *TgMessage) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *TgMessage) GetEntities() []*MessageEntity {
	if m != nil {
		return m.Entities
	}
	return nil
}

func (m *TgMessage) GetAudio() *TgAudio {
	if m != nil {
		return m.Audio
	}
	return nil
}

func (m *TgMessage) GetDocument() *TgDocument {
	if m != nil {
		return m.Document
	}
	return nil
}

func (m *TgMessage) GetPhoto() []*TgPhotoSize {
	if m != nil {
		return m.Photo
	}
	return nil
}

func (m *TgMessage) GetSticker() *TgSticker {
	if m != nil {
		return m.Sticker
	}
	return nil
}

func (m *TgMessage) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

func (m *TgMessage) GetNewChatMembers() []*TgUser {
	if m != nil {
		return m.NewChatMembers
	}
	return nil
}

func (m *TgMessage) GetLeftChatMember() *TgUser {
	if m != nil {
		return m.LeftChatMember
	}
	return nil
}

func (m *TgMessage) GetNewChatTitle() string {
	if m != nil {
		return m.NewChatTitle
	}
	return ""
}

func (m *TgMessage) GetNewChatPhoto() []*TgPhotoSize {
	if m != nil {
		return m.NewChatPhoto
	}
	return nil
}

func (m *TgMessage) GetDeleteChatPhoto() bool {
	if m != nil {
		return m.DeleteChatPhoto
	}
	return false
}

func (m *TgMessage) GetGroupChatCreated() bool {
	if m != nil {
		return m.GroupChatCreated
	}
	return false
}

func (m *TgMessage) GetSuperGroupChatCreated() bool {
	if m != nil {
		return m.SuperGroupChatCreated
	}
	return false
}

func (m *TgMessage) GetChannelChatCreated() bool {
	if m != nil {
		return m.ChannelChatCreated
	}
	return false
}

func (m *TgMessage) GetMigrateToChatID() int64 {
	if m != nil {
		return m.MigrateToChatID
	}
	return 0
}

func (m *TgMessage) GetMigrateFromChatID() int64 {
	if m != nil {
		return m.MigrateFromChatID
	}
	return 0
}

func (m *TgMessage) GetPinnedMessage() *TgMessage {
	if m != nil {
		return m.PinnedMessage
	}
	return nil
}

type TgSticker struct {
	FileId               string         `protobuf:"bytes,1,opt,name=FileId,proto3" json:"FileId,omitempty"`
	Wifth                int32          `protobuf:"varint,2,opt,name=Wifth,proto3" json:"Wifth,omitempty"`
	Height               int32          `protobuf:"varint,3,opt,name=Height,proto3" json:"Height,omitempty"`
	Thumbnail            []*TgPhotoSize `protobuf:"bytes,4,rep,name=Thumbnail,proto3" json:"Thumbnail,omitempty"`
	Emoji                string         `protobuf:"bytes,5,opt,name=Emoji,proto3" json:"Emoji,omitempty"`
	FileSize             int32          `protobuf:"varint,6,opt,name=FileSize,proto3" json:"FileSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TgSticker) Reset()         { *m = TgSticker{} }
func (m *TgSticker) String() string { return proto.CompactTextString(m) }
func (*TgSticker) ProtoMessage()    {}
func (*TgSticker) Descriptor() ([]byte, []int) {
	return fileDescriptor_tg_7cb0180f9eac2d34, []int{3}
}
func (m *TgSticker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TgSticker.Unmarshal(m, b)
}
func (m *TgSticker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TgSticker.Marshal(b, m, deterministic)
}
func (dst *TgSticker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TgSticker.Merge(dst, src)
}
func (m *TgSticker) XXX_Size() int {
	return xxx_messageInfo_TgSticker.Size(m)
}
func (m *TgSticker) XXX_DiscardUnknown() {
	xxx_messageInfo_TgSticker.DiscardUnknown(m)
}

var xxx_messageInfo_TgSticker proto.InternalMessageInfo

func (m *TgSticker) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

func (m *TgSticker) GetWifth() int32 {
	if m != nil {
		return m.Wifth
	}
	return 0
}

func (m *TgSticker) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *TgSticker) GetThumbnail() []*TgPhotoSize {
	if m != nil {
		return m.Thumbnail
	}
	return nil
}

func (m *TgSticker) GetEmoji() string {
	if m != nil {
		return m.Emoji
	}
	return ""
}

func (m *TgSticker) GetFileSize() int32 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

type TgDocument struct {
	FileId               string       `protobuf:"bytes,1,opt,name=FileId,proto3" json:"FileId,omitempty"`
	Thumbnail            *TgPhotoSize `protobuf:"bytes,2,opt,name=Thumbnail,proto3" json:"Thumbnail,omitempty"`
	FileName             string       `protobuf:"bytes,3,opt,name=FileName,proto3" json:"FileName,omitempty"`
	MimeType             string       `protobuf:"bytes,4,opt,name=MimeType,proto3" json:"MimeType,omitempty"`
	FileSize             int32        `protobuf:"varint,5,opt,name=FileSize,proto3" json:"FileSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TgDocument) Reset()         { *m = TgDocument{} }
func (m *TgDocument) String() string { return proto.CompactTextString(m) }
func (*TgDocument) ProtoMessage()    {}
func (*TgDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_tg_7cb0180f9eac2d34, []int{4}
}
func (m *TgDocument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TgDocument.Unmarshal(m, b)
}
func (m *TgDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TgDocument.Marshal(b, m, deterministic)
}
func (dst *TgDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TgDocument.Merge(dst, src)
}
func (m *TgDocument) XXX_Size() int {
	return xxx_messageInfo_TgDocument.Size(m)
}
func (m *TgDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_TgDocument.DiscardUnknown(m)
}

var xxx_messageInfo_TgDocument proto.InternalMessageInfo

func (m *TgDocument) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

func (m *TgDocument) GetThumbnail() *TgPhotoSize {
	if m != nil {
		return m.Thumbnail
	}
	return nil
}

func (m *TgDocument) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *TgDocument) GetMimeType() string {
	if m != nil {
		return m.MimeType
	}
	return ""
}

func (m *TgDocument) GetFileSize() int32 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

type TgPhotoSize struct {
	FileID               string   `protobuf:"bytes,1,opt,name=FileID,proto3" json:"FileID,omitempty"`
	Width                int32    `protobuf:"varint,2,opt,name=Width,proto3" json:"Width,omitempty"`
	Height               int32    `protobuf:"varint,3,opt,name=Height,proto3" json:"Height,omitempty"`
	FileSize             int32    `protobuf:"varint,4,opt,name=FileSize,proto3" json:"FileSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TgPhotoSize) Reset()         { *m = TgPhotoSize{} }
func (m *TgPhotoSize) String() string { return proto.CompactTextString(m) }
func (*TgPhotoSize) ProtoMessage()    {}
func (*TgPhotoSize) Descriptor() ([]byte, []int) {
	return fileDescriptor_tg_7cb0180f9eac2d34, []int{5}
}
func (m *TgPhotoSize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TgPhotoSize.Unmarshal(m, b)
}
func (m *TgPhotoSize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TgPhotoSize.Marshal(b, m, deterministic)
}
func (dst *TgPhotoSize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TgPhotoSize.Merge(dst, src)
}
func (m *TgPhotoSize) XXX_Size() int {
	return xxx_messageInfo_TgPhotoSize.Size(m)
}
func (m *TgPhotoSize) XXX_DiscardUnknown() {
	xxx_messageInfo_TgPhotoSize.DiscardUnknown(m)
}

var xxx_messageInfo_TgPhotoSize proto.InternalMessageInfo

func (m *TgPhotoSize) GetFileID() string {
	if m != nil {
		return m.FileID
	}
	return ""
}

func (m *TgPhotoSize) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *TgPhotoSize) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *TgPhotoSize) GetFileSize() int32 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

type TgAudio struct {
	FileID               string   `protobuf:"bytes,1,opt,name=FileID,proto3" json:"FileID,omitempty"`
	Duration             int32    `protobuf:"varint,2,opt,name=Duration,proto3" json:"Duration,omitempty"`
	Performer            string   `protobuf:"bytes,3,opt,name=Performer,proto3" json:"Performer,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=Title,proto3" json:"Title,omitempty"`
	MimeType             string   `protobuf:"bytes,5,opt,name=MimeType,proto3" json:"MimeType,omitempty"`
	FileSize             int32    `protobuf:"varint,6,opt,name=FileSize,proto3" json:"FileSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TgAudio) Reset()         { *m = TgAudio{} }
func (m *TgAudio) String() string { return proto.CompactTextString(m) }
func (*TgAudio) ProtoMessage()    {}
func (*TgAudio) Descriptor() ([]byte, []int) {
	return fileDescriptor_tg_7cb0180f9eac2d34, []int{6}
}
func (m *TgAudio) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TgAudio.Unmarshal(m, b)
}
func (m *TgAudio) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TgAudio.Marshal(b, m, deterministic)
}
func (dst *TgAudio) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TgAudio.Merge(dst, src)
}
func (m *TgAudio) XXX_Size() int {
	return xxx_messageInfo_TgAudio.Size(m)
}
func (m *TgAudio) XXX_DiscardUnknown() {
	xxx_messageInfo_TgAudio.DiscardUnknown(m)
}

var xxx_messageInfo_TgAudio proto.InternalMessageInfo

func (m *TgAudio) GetFileID() string {
	if m != nil {
		return m.FileID
	}
	return ""
}

func (m *TgAudio) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *TgAudio) GetPerformer() string {
	if m != nil {
		return m.Performer
	}
	return ""
}

func (m *TgAudio) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TgAudio) GetMimeType() string {
	if m != nil {
		return m.MimeType
	}
	return ""
}

func (m *TgAudio) GetFileSize() int32 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

type MessageEntity struct {
	Type                 string   `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Length               int32    `protobuf:"varint,3,opt,name=Length,proto3" json:"Length,omitempty"`
	URL                  string   `protobuf:"bytes,4,opt,name=URL,proto3" json:"URL,omitempty"`
	User                 *TgUser  `protobuf:"bytes,5,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageEntity) Reset()         { *m = MessageEntity{} }
func (m *MessageEntity) String() string { return proto.CompactTextString(m) }
func (*MessageEntity) ProtoMessage()    {}
func (*MessageEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_tg_7cb0180f9eac2d34, []int{7}
}
func (m *MessageEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageEntity.Unmarshal(m, b)
}
func (m *MessageEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageEntity.Marshal(b, m, deterministic)
}
func (dst *MessageEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageEntity.Merge(dst, src)
}
func (m *MessageEntity) XXX_Size() int {
	return xxx_messageInfo_MessageEntity.Size(m)
}
func (m *MessageEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageEntity.DiscardUnknown(m)
}

var xxx_messageInfo_MessageEntity proto.InternalMessageInfo

func (m *MessageEntity) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *MessageEntity) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *MessageEntity) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *MessageEntity) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *MessageEntity) GetUser() *TgUser {
	if m != nil {
		return m.User
	}
	return nil
}

type TgFrom struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=LastName,proto3" json:"LastName,omitempty"`
	UserName             string   `protobuf:"bytes,4,opt,name=UserName,proto3" json:"UserName,omitempty"`
	LanguageCode         string   `protobuf:"bytes,5,opt,name=LanguageCode,proto3" json:"LanguageCode,omitempty"`
	IsBot                bool     `protobuf:"varint,6,opt,name=isBot,proto3" json:"isBot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TgFrom) Reset()         { *m = TgFrom{} }
func (m *TgFrom) String() string { return proto.CompactTextString(m) }
func (*TgFrom) ProtoMessage()    {}
func (*TgFrom) Descriptor() ([]byte, []int) {
	return fileDescriptor_tg_7cb0180f9eac2d34, []int{8}
}
func (m *TgFrom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TgFrom.Unmarshal(m, b)
}
func (m *TgFrom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TgFrom.Marshal(b, m, deterministic)
}
func (dst *TgFrom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TgFrom.Merge(dst, src)
}
func (m *TgFrom) XXX_Size() int {
	return xxx_messageInfo_TgFrom.Size(m)
}
func (m *TgFrom) XXX_DiscardUnknown() {
	xxx_messageInfo_TgFrom.DiscardUnknown(m)
}

var xxx_messageInfo_TgFrom proto.InternalMessageInfo

func (m *TgFrom) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *TgFrom) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *TgFrom) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *TgFrom) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *TgFrom) GetLanguageCode() string {
	if m != nil {
		return m.LanguageCode
	}
	return ""
}

func (m *TgFrom) GetIsBot() bool {
	if m != nil {
		return m.IsBot
	}
	return false
}

type TgChat struct {
	ID                   int64        `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Type                 string       `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Title                string       `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	UserName             string       `protobuf:"bytes,4,opt,name=UserName,proto3" json:"UserName,omitempty"`
	FirstName            string       `protobuf:"bytes,5,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string       `protobuf:"bytes,6,opt,name=LastName,proto3" json:"LastName,omitempty"`
	AllMembersAreAdmins  bool         `protobuf:"varint,7,opt,name=AllMembersAreAdmins,proto3" json:"AllMembersAreAdmins,omitempty"`
	Photo                *TgChatPhoto `protobuf:"bytes,8,opt,name=Photo,proto3" json:"Photo,omitempty"`
	Description          string       `protobuf:"bytes,9,opt,name=Description,proto3" json:"Description,omitempty"`
	InviteLink           string       `protobuf:"bytes,10,opt,name=InviteLink,proto3" json:"InviteLink,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TgChat) Reset()         { *m = TgChat{} }
func (m *TgChat) String() string { return proto.CompactTextString(m) }
func (*TgChat) ProtoMessage()    {}
func (*TgChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_tg_7cb0180f9eac2d34, []int{9}
}
func (m *TgChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TgChat.Unmarshal(m, b)
}
func (m *TgChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TgChat.Marshal(b, m, deterministic)
}
func (dst *TgChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TgChat.Merge(dst, src)
}
func (m *TgChat) XXX_Size() int {
	return xxx_messageInfo_TgChat.Size(m)
}
func (m *TgChat) XXX_DiscardUnknown() {
	xxx_messageInfo_TgChat.DiscardUnknown(m)
}

var xxx_messageInfo_TgChat proto.InternalMessageInfo

func (m *TgChat) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *TgChat) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TgChat) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TgChat) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *TgChat) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *TgChat) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *TgChat) GetAllMembersAreAdmins() bool {
	if m != nil {
		return m.AllMembersAreAdmins
	}
	return false
}

func (m *TgChat) GetPhoto() *TgChatPhoto {
	if m != nil {
		return m.Photo
	}
	return nil
}

func (m *TgChat) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TgChat) GetInviteLink() string {
	if m != nil {
		return m.InviteLink
	}
	return ""
}

type TgChatPhoto struct {
	SmallFileID          string   `protobuf:"bytes,1,opt,name=SmallFileID,proto3" json:"SmallFileID,omitempty"`
	BigFileID            string   `protobuf:"bytes,2,opt,name=BigFileID,proto3" json:"BigFileID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TgChatPhoto) Reset()         { *m = TgChatPhoto{} }
func (m *TgChatPhoto) String() string { return proto.CompactTextString(m) }
func (*TgChatPhoto) ProtoMessage()    {}
func (*TgChatPhoto) Descriptor() ([]byte, []int) {
	return fileDescriptor_tg_7cb0180f9eac2d34, []int{10}
}
func (m *TgChatPhoto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TgChatPhoto.Unmarshal(m, b)
}
func (m *TgChatPhoto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TgChatPhoto.Marshal(b, m, deterministic)
}
func (dst *TgChatPhoto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TgChatPhoto.Merge(dst, src)
}
func (m *TgChatPhoto) XXX_Size() int {
	return xxx_messageInfo_TgChatPhoto.Size(m)
}
func (m *TgChatPhoto) XXX_DiscardUnknown() {
	xxx_messageInfo_TgChatPhoto.DiscardUnknown(m)
}

var xxx_messageInfo_TgChatPhoto proto.InternalMessageInfo

func (m *TgChatPhoto) GetSmallFileID() string {
	if m != nil {
		return m.SmallFileID
	}
	return ""
}

func (m *TgChatPhoto) GetBigFileID() string {
	if m != nil {
		return m.BigFileID
	}
	return ""
}

type TgUser struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=LastName,proto3" json:"LastName,omitempty"`
	UserName             string   `protobuf:"bytes,4,opt,name=UserName,proto3" json:"UserName,omitempty"`
	LanguageCode         string   `protobuf:"bytes,5,opt,name=LanguageCode,proto3" json:"LanguageCode,omitempty"`
	IsBot                bool     `protobuf:"varint,6,opt,name=IsBot,proto3" json:"IsBot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TgUser) Reset()         { *m = TgUser{} }
func (m *TgUser) String() string { return proto.CompactTextString(m) }
func (*TgUser) ProtoMessage()    {}
func (*TgUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_tg_7cb0180f9eac2d34, []int{11}
}
func (m *TgUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TgUser.Unmarshal(m, b)
}
func (m *TgUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TgUser.Marshal(b, m, deterministic)
}
func (dst *TgUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TgUser.Merge(dst, src)
}
func (m *TgUser) XXX_Size() int {
	return xxx_messageInfo_TgUser.Size(m)
}
func (m *TgUser) XXX_DiscardUnknown() {
	xxx_messageInfo_TgUser.DiscardUnknown(m)
}

var xxx_messageInfo_TgUser proto.InternalMessageInfo

func (m *TgUser) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *TgUser) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *TgUser) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *TgUser) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *TgUser) GetLanguageCode() string {
	if m != nil {
		return m.LanguageCode
	}
	return ""
}

func (m *TgUser) GetIsBot() bool {
	if m != nil {
		return m.IsBot
	}
	return false
}

func init() {
	proto.RegisterType((*Response)(nil), "proto.Response")
	proto.RegisterType((*TgUpdate)(nil), "proto.TgUpdate")
	proto.RegisterType((*TgMessage)(nil), "proto.TgMessage")
	proto.RegisterType((*TgSticker)(nil), "proto.TgSticker")
	proto.RegisterType((*TgDocument)(nil), "proto.TgDocument")
	proto.RegisterType((*TgPhotoSize)(nil), "proto.TgPhotoSize")
	proto.RegisterType((*TgAudio)(nil), "proto.TgAudio")
	proto.RegisterType((*MessageEntity)(nil), "proto.MessageEntity")
	proto.RegisterType((*TgFrom)(nil), "proto.TgFrom")
	proto.RegisterType((*TgChat)(nil), "proto.TgChat")
	proto.RegisterType((*TgChatPhoto)(nil), "proto.TgChatPhoto")
	proto.RegisterType((*TgUser)(nil), "proto.TgUser")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommandsClient is the client API for Commands service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommandsClient interface {
	Command(ctx context.Context, in *TgUpdate, opts ...grpc.CallOption) (*Response, error)
}

type commandsClient struct {
	cc *grpc.ClientConn
}

func NewCommandsClient(cc *grpc.ClientConn) CommandsClient {
	return &commandsClient{cc}
}

func (c *commandsClient) Command(ctx context.Context, in *TgUpdate, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.Commands/Command", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommandsServer is the server API for Commands service.
type CommandsServer interface {
	Command(context.Context, *TgUpdate) (*Response, error)
}

func RegisterCommandsServer(s *grpc.Server, srv CommandsServer) {
	s.RegisterService(&_Commands_serviceDesc, srv)
}

func _Commands_Command_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TgUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandsServer).Command(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Commands/Command",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandsServer).Command(ctx, req.(*TgUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

var _Commands_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Commands",
	HandlerType: (*CommandsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Command",
			Handler:    _Commands_Command_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tg.proto",
}

func init() { proto.RegisterFile("tg.proto", fileDescriptor_tg_7cb0180f9eac2d34) }

var fileDescriptor_tg_7cb0180f9eac2d34 = []byte{
	// 1080 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xdd, 0x6e, 0xe3, 0xc4,
	0x17, 0xff, 0x3b, 0x89, 0x53, 0xfb, 0x64, 0xfb, 0x35, 0xdb, 0xed, 0xdf, 0x94, 0x15, 0x0a, 0x16,
	0x17, 0xd1, 0x8a, 0xad, 0xaa, 0x2e, 0x54, 0x20, 0xae, 0xba, 0x71, 0x0b, 0x91, 0x92, 0xa5, 0x9a,
	0xa6, 0xe2, 0xda, 0xad, 0x4f, 0x93, 0x61, 0x63, 0x3b, 0xb2, 0x27, 0x2c, 0xe5, 0x09, 0x78, 0x14,
	0xe0, 0x1e, 0x1e, 0x81, 0xe7, 0x42, 0x73, 0x3c, 0x9e, 0xc4, 0x6e, 0x52, 0x2e, 0xb9, 0xf2, 0x9c,
	0xdf, 0xf9, 0xcd, 0x9c, 0x33, 0x67, 0xce, 0x87, 0xc1, 0x91, 0x93, 0xe3, 0x79, 0x96, 0xca, 0x94,
	0xd9, 0xf4, 0xf1, 0x7d, 0x70, 0x38, 0xe6, 0xf3, 0x34, 0xc9, 0x91, 0x1d, 0x42, 0x3b, 0x97, 0xa1,
	0x5c, 0xe4, 0x9e, 0xd5, 0xb5, 0x7a, 0x0e, 0xd7, 0x92, 0xcf, 0xc1, 0x19, 0x4f, 0x6e, 0xe6, 0x51,
	0x28, 0x91, 0x1d, 0x81, 0x53, 0xac, 0x06, 0x01, 0xb1, 0x6c, 0x6e, 0x64, 0xf6, 0x0a, 0xb6, 0x46,
	0x98, 0xe7, 0xe1, 0x04, 0xbd, 0x46, 0xd7, 0xea, 0x75, 0x4e, 0xf7, 0x0a, 0x5b, 0xc7, 0xe3, 0x89,
	0xc6, 0x79, 0x49, 0xf0, 0xff, 0x76, 0xc1, 0x35, 0x30, 0x7b, 0x09, 0x6e, 0x5c, 0x2c, 0xf5, 0xb1,
	0x2d, 0xbe, 0x04, 0xd8, 0xa7, 0xd0, 0xba, 0xcc, 0xd2, 0x58, 0x1f, 0xba, 0x6d, 0x0e, 0x55, 0x20,
	0x27, 0x15, 0x63, 0xd0, 0x0a, 0x42, 0x89, 0x5e, 0x93, 0x5c, 0xa2, 0xb5, 0xda, 0xd6, 0x9f, 0x86,
	0xd2, 0x6b, 0xd5, 0xb6, 0x29, 0x90, 0x93, 0x8a, 0xbd, 0x81, 0xed, 0xcb, 0x34, 0xfb, 0x10, 0x66,
	0x11, 0x46, 0x64, 0xc2, 0xae, 0x71, 0x6f, 0x72, 0xcc, 0x78, 0x95, 0xc3, 0xbe, 0x81, 0xfd, 0x0a,
	0x40, 0x46, 0xda, 0xeb, 0x8c, 0x3c, 0xe6, 0xb1, 0x33, 0x38, 0xac, 0x80, 0x23, 0x73, 0xed, 0xad,
	0xae, 0xd5, 0x6b, 0xf2, 0x0d, 0x5a, 0xd6, 0x85, 0x8e, 0xd6, 0xd0, 0x3d, 0x1d, 0x8a, 0xd1, 0x2a,
	0xc4, 0xbe, 0x82, 0x1d, 0x8e, 0xf3, 0xd9, 0xc3, 0x38, 0x2d, 0x1f, 0xc1, 0xdd, 0xf0, 0x08, 0x35,
	0x9e, 0x7a, 0xd3, 0x8b, 0x48, 0x48, 0x3a, 0x18, 0xe8, 0x60, 0x23, 0xab, 0xc0, 0x8e, 0xf1, 0x67,
	0xe9, 0x75, 0xba, 0x56, 0xcf, 0xe5, 0xb4, 0x66, 0x27, 0xe0, 0x5c, 0x24, 0x52, 0x48, 0x81, 0xb9,
	0xf7, 0xac, 0xdb, 0xec, 0x75, 0x4e, 0x0f, 0xb4, 0x0d, 0x7d, 0x22, 0x69, 0x1f, 0xb8, 0x61, 0xb1,
	0xcf, 0xc0, 0x3e, 0x5f, 0x44, 0x22, 0xf5, 0xb6, 0xc9, 0xa5, 0x1d, 0xe3, 0x12, 0xa1, 0xbc, 0x50,
	0xb2, 0xd7, 0xe0, 0x04, 0xe9, 0xdd, 0x22, 0xc6, 0x44, 0x7a, 0x3b, 0x44, 0xdc, 0x37, 0xc4, 0x52,
	0xc1, 0x0d, 0x85, 0xf5, 0xc0, 0xbe, 0x9a, 0xa6, 0x32, 0xf5, 0x76, 0xc9, 0x07, 0x66, 0xb8, 0x84,
	0x5e, 0x8b, 0x5f, 0x90, 0x17, 0x04, 0x95, 0x98, 0xd7, 0x52, 0xdc, 0xbd, 0xc7, 0xcc, 0xdb, 0xab,
	0xc5, 0x44, 0xe3, 0xbc, 0x24, 0x30, 0x0f, 0xb6, 0xfa, 0xe1, 0x5c, 0x8a, 0x34, 0xf1, 0xf6, 0xe9,
	0xce, 0xa5, 0xc8, 0xbe, 0x84, 0x9d, 0x77, 0xf8, 0x41, 0xbd, 0xe2, 0x08, 0xe3, 0x5b, 0xcc, 0x72,
	0x8f, 0x91, 0xe1, 0x5a, 0xb6, 0xd4, 0x48, 0x6a, 0xdb, 0x10, 0xef, 0xe5, 0x12, 0xf2, 0x9e, 0xaf,
	0x4b, 0xb2, 0x1a, 0x89, 0xf9, 0xf0, 0x4c, 0x1f, 0x34, 0x16, 0x72, 0x86, 0xde, 0x01, 0x39, 0x53,
	0xc1, 0xd8, 0x99, 0xe1, 0x14, 0x81, 0x78, 0xb1, 0x31, 0x10, 0x15, 0x1e, 0xeb, 0xc1, 0x6e, 0x80,
	0x33, 0x94, 0xb8, 0xdc, 0x7a, 0x48, 0x15, 0x5f, 0x87, 0xd9, 0x2b, 0xd8, 0xfb, 0x36, 0x4b, 0x17,
	0x73, 0x85, 0xf4, 0x33, 0x0c, 0x25, 0x46, 0xde, 0xff, 0x89, 0xfa, 0x08, 0x67, 0x5f, 0xc0, 0x8b,
	0xeb, 0xc5, 0x1c, 0xb3, 0x47, 0x1b, 0x3c, 0xda, 0xb0, 0x5e, 0xc9, 0x8e, 0x81, 0xf5, 0xa7, 0x61,
	0x92, 0xe0, 0x6c, 0x75, 0xcb, 0x47, 0xb4, 0x65, 0x8d, 0x46, 0xf9, 0x3e, 0x12, 0x93, 0x2c, 0x94,
	0x38, 0x4e, 0x15, 0x3e, 0x08, 0xbc, 0x23, 0xaa, 0x9c, 0x3a, 0xcc, 0x3e, 0x87, 0x7d, 0x0d, 0x95,
	0xd5, 0x37, 0x08, 0xbc, 0x8f, 0x89, 0xfb, 0x58, 0xc1, 0xce, 0x60, 0xfb, 0x4a, 0x24, 0x09, 0x46,
	0x65, 0xf5, 0xbc, 0xdc, 0x50, 0x3d, 0x55, 0x9a, 0xff, 0xa7, 0xa5, 0x1a, 0x59, 0x99, 0x3d, 0x87,
	0xd0, 0xbe, 0x14, 0x33, 0x1c, 0x44, 0xd4, 0xc5, 0x5c, 0xae, 0x25, 0x76, 0x00, 0xf6, 0x0f, 0xe2,
	0x5e, 0x4e, 0xa9, 0x87, 0xd9, 0xbc, 0x10, 0x14, 0xfb, 0x3b, 0x14, 0x93, 0xa9, 0xd4, 0x7d, 0x4b,
	0x4b, 0xec, 0x04, 0xdc, 0xf1, 0x74, 0x11, 0xdf, 0x26, 0xa1, 0x98, 0x79, 0xad, 0x8d, 0x8f, 0xba,
	0x24, 0xa9, 0xf3, 0x2f, 0xe2, 0xf4, 0x47, 0x41, 0x0d, 0xcc, 0xe5, 0x85, 0xa0, 0x0a, 0x5b, 0xd9,
	0x57, 0x64, 0x6a, 0x50, 0x36, 0x37, 0xb2, 0xff, 0x87, 0x05, 0xb0, 0x2c, 0xab, 0x8d, 0x8e, 0x57,
	0x5c, 0x29, 0x1a, 0xf0, 0xbf, 0xb8, 0xa2, 0x8d, 0xbe, 0x0b, 0xe3, 0xa2, 0x1d, 0xbb, 0xdc, 0xc8,
	0x4a, 0x37, 0x12, 0x31, 0x8e, 0x1f, 0xe6, 0x48, 0x6d, 0xd9, 0xe5, 0x46, 0xae, 0x38, 0x6b, 0xd7,
	0x9c, 0x4d, 0xa1, 0xb3, 0x62, 0xcd, 0x38, 0x1b, 0x54, 0x9c, 0x0d, 0x8a, 0x28, 0x47, 0xab, 0x51,
	0x8e, 0x9e, 0x88, 0xf2, 0xaa, 0xc1, 0x56, 0xcd, 0xe0, 0xef, 0x16, 0x6c, 0xe9, 0xee, 0xb4, 0xd1,
	0xda, 0x11, 0x38, 0xc1, 0x22, 0x0b, 0xa9, 0x55, 0x14, 0x06, 0x8d, 0xac, 0x06, 0xda, 0x15, 0x66,
	0xf7, 0x69, 0x16, 0x63, 0xa6, 0xa3, 0xb0, 0x04, 0x94, 0x9f, 0x45, 0x51, 0x17, 0x31, 0x28, 0x84,
	0x4a, 0x70, 0xec, 0x27, 0x82, 0x53, 0x7f, 0xc9, 0x5f, 0x2d, 0xd8, 0xae, 0x34, 0x5e, 0x6a, 0xda,
	0xea, 0x14, 0x4b, 0x37, 0x6d, 0x75, 0xc2, 0x21, 0xb4, 0xbf, 0xbf, 0xbf, 0xcf, 0x51, 0x6a, 0x5f,
	0xb5, 0xa4, 0xf0, 0x21, 0x26, 0x13, 0x39, 0x2d, 0xa3, 0x53, 0x48, 0x6c, 0x0f, 0x9a, 0x37, 0x7c,
	0xa8, 0x3d, 0x54, 0x4b, 0x35, 0x4f, 0x55, 0xa7, 0x5a, 0x3f, 0x23, 0x49, 0xe5, 0xff, 0x66, 0x41,
	0xbb, 0x98, 0xcb, 0x6c, 0x07, 0x1a, 0x66, 0x96, 0x37, 0x06, 0x81, 0x8a, 0xc8, 0xa5, 0xc8, 0x72,
	0x49, 0x79, 0xd1, 0x28, 0x22, 0x62, 0x00, 0x75, 0xbf, 0x61, 0xa8, 0x95, 0x3a, 0x69, 0x4a, 0x99,
	0x7e, 0x39, 0x72, 0xcc, 0x48, 0xa7, 0x93, 0xa6, 0x94, 0x55, 0x97, 0x1c, 0x86, 0xc9, 0x64, 0x11,
	0x4e, 0xb0, 0x9f, 0x46, 0x65, 0xdc, 0x2a, 0x98, 0x8a, 0xb6, 0xc8, 0xdf, 0xa6, 0xc5, 0x8c, 0x76,
	0x78, 0x21, 0xf8, 0x7f, 0x35, 0x94, 0xab, 0x34, 0x93, 0x97, 0xae, 0x36, 0xc9, 0xd5, 0x32, 0x7c,
	0x8d, 0x95, 0xf0, 0x99, 0x27, 0x6b, 0xd6, 0x9e, 0x6c, 0xa3, 0x6b, 0x95, 0x0b, 0xdb, 0x4f, 0x5d,
	0xb8, 0x5d, 0xbb, 0xf0, 0x09, 0x3c, 0x3f, 0x9f, 0xcd, 0xf4, 0xfc, 0x38, 0xcf, 0xf0, 0x3c, 0x8a,
	0x45, 0x92, 0xd3, 0x0f, 0x82, 0xc3, 0xd7, 0xa9, 0x96, 0xa3, 0xd0, 0xa9, 0x55, 0xa8, 0xe9, 0xe4,
	0xe5, 0x28, 0xec, 0x42, 0x27, 0xc0, 0xfc, 0x2e, 0x13, 0xc5, 0x88, 0x73, 0xc9, 0xf4, 0x2a, 0xc4,
	0x3e, 0x01, 0x18, 0x24, 0x3f, 0x09, 0x89, 0x43, 0x91, 0xbc, 0xa7, 0xff, 0x01, 0x97, 0xaf, 0x20,
	0xfe, 0x48, 0xd5, 0xe2, 0x72, 0x42, 0x74, 0xa1, 0x73, 0x1d, 0x87, 0xb3, 0x59, 0xa5, 0x44, 0x56,
	0x21, 0x15, 0x88, 0xb7, 0x62, 0xa2, 0xf5, 0xfa, 0xe5, 0x0d, 0xa0, 0x53, 0x46, 0x45, 0xed, 0xd1,
	0x3b, 0xfc, 0xa7, 0x29, 0x33, 0x58, 0x4d, 0x19, 0x12, 0x4e, 0xbf, 0x06, 0xa7, 0x9f, 0xc6, 0x71,
	0x98, 0x44, 0x39, 0x7b, 0x0d, 0x5b, 0x7a, 0xcd, 0x76, 0x97, 0x95, 0x40, 0x7f, 0xc2, 0x47, 0x25,
	0x50, 0xfe, 0x58, 0xfb, 0xff, 0xbb, 0x6d, 0x13, 0xf2, 0xe6, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xc6, 0x0a, 0xb5, 0xaf, 0x80, 0x0b, 0x00, 0x00,
}
